export const  PRODUCT_ACTION_TYPES = {
    FETCH_PRODUCT_START: 'product/FETCH_CATEGORIES_START',
    FETCH_PRODUCT_SUCCESS: 'product/FETCH_CATEGORIES_SUCCESS',
    FETCH_PRODUCT_FAILED: 'product/FETCH_CATEGORIES_FAILED',
};