export const  ORDER_LIST_MY_ACTION_TYPES = {
     ORDER_LIST_MY_REQUEST : 'ORDER_LIST_REQUEST',
     ORDER_LIST_MY_SUCCESS : 'ORDER_LIST_SUCCESS',
     ORDER_LIST_MY_FAIL : 'ORDER_LIST_FAIL',
     ORDER_LIST_MY_RESET : 'ORDER_LIST_MY_RESET'
};