export const  PRODUCT_Details_ACTION_TYPES = {
    FETCH_PRODUCT_Details_START: 'product/FETCH_CATEGORIES_Details_START',
    FETCH_PRODUCT_Details_SUCCESS: 'product/FETCH_CATEGORIES_Details_SUCCESS',
    FETCH_PRODUCT_Details_FAILED: 'product/FETCH_CATEGORIES_Details_FAILED',
};