export const USER_DETAILS_ACTION_TYPES = {
    USER_DETAILS_REQUEST: 'USER/DETAILS/START',
    USER_DETAILS_SUCCESS: 'USER/DETAILS/SUCCESS',
    USER_DETAILS_FAIL: 'USER/DETAILS/FAIL',
    USER_DETAILS_RESET: 'USER/DETAILS/RESET'
};