export const PRODUCT_DELETE_ACTION_TYPES = {
     PRODUCT_DELETE_REQUEST : 'PRODUCT_DELETE_REQUEST',
     PRODUCT_DELETE_SUCCESS : 'PRODUCT_DELETE_SUCCESS',
     PRODUCT_DELETE_FAIL : 'PRODUCT_DELETE_FAIL'
   }