export const PRODUCT_REVIEW = {
    PRODUCT_CREATE_REVIEW_REQUEST : 'PRODUCT_CREATE_REVIEW_REQUEST',
    PRODUCT_CREATE_REVIEW_SUCCESS : 'PRODUCT_CREATE_REVIEW_SUCCESS',
    PRODUCT_CREATE_REVIEW_FAIL : 'PRODUCT_CREATE_REVIEW_FAIL',
    PRODUCT_CREATE_REVIEW_RESET : 'PRODUCT_CREATE_REVIEW_RESET'
   }