export const USER_DETAILS_UPDATE_ACTION_TYPES = {
     USER_UPDATE_REQUEST : 'USER_UPDATE_REQUEST',
     USER_UPDATE_SUCCESS : 'USER_UPDATE_SUCCESS',
     USER_UPDATE_FAIL : 'USER_UPDATE_FAIL',
     USER_UPDATE_RESET : 'USER_UPDATE_RESET'
};