export const PRODUCT_UPDATE_ACTION_TYPES = {
     PRODUCT_UPDATE_REQUEST : 'PRODUCT_UPDATE_REQUEST',
     PRODUCT_UPDATE_SUCCESS : 'PRODUCT_UPDATE_SUCCESS',
     PRODUCT_UPDATE_FAIL : 'PRODUCT_UPDATE_FAIL',
     PRODUCT_UPDATE_RESET : 'PRODUCT_UPDATE_RESET'
   }