export const USER_LIST_ACTION_TYPES = {
     USER_LIST_REQUEST : 'USER_LIST_REQUEST',
     USER_LIST_SUCCESS : 'USER_LIST_SUCCESS',
     USER_LIST_FAIL : 'USER_LIST_FAIL',
     USER_LIST_RESET : 'USER_LIST_RESET'
};
