export const USER_PROFILE_ACTION_TYPES = {
    USER_PROFILE_REQUEST: 'USER/PROFILE/START',
    USER_PROFILE_SUCCESS: 'USER/PROFILE/SUCCESS',
    USER_PROFILE_FAIL: 'USER/PROFILE/FAIL',
    USER_PROFILE_RESET: 'USER/PROFILE/RESET',
};