export const  ORDER_DETAILS_ACTION_TYPES = {
     ORDER_DETAILS_REQUEST : 'ORDER_DETAILS_REQUEST',
     ORDER_DETAILS_SUCCESS : 'ORDER_DETAILS_SUCCESS',
     ORDER_DETAILS_FAIL : 'ORDER_DETAILS_FAIL'
};

 