export const  ORDER_PAY_ACTION_TYPES = {
     ORDER_PAY_REQUEST : 'ORDER_PAY_REQUEST',
     ORDER_PAY_SUCCESS : 'ORDER_PAY_SUCCESS',
     ORDER_PAY_FAIL : 'ORDER_PAY_FAIL',
     ORDER_PAY_RESET : 'ORDER_PAY_RESET'
};