export const ORDER_DELIVER_ACTION = {
 ORDER_DELIVER_REQUEST : 'ORDER_DELIVER_REQUEST',
 ORDER_DELIVER_SUCCESS : 'ORDER_DELIVER_SUCCESS',
 ORDER_DELIVER_FAIL : 'ORDER_DELIVER_FAIL',
 ORDER_DELIVER_RESET : 'ORDER_DELIVER_RESET'
}