 export const PRODUCT_CREATE_ACTION_TYPES = {
 PRODUCT_CREATE_REQUEST : 'PRODUCT_CREATE_REQUEST',
 PRODUCT_CREATE_SUCCESS : 'PRODUCT_CREATE_SUCCESS',
 PRODUCT_CREATE_FAIL : 'PRODUCT_CREATE_FAIL',
 PRODUCT_CREATE_RESET : 'PRODUCT_CREATE_RESET'
}